project_name: Nengo
pkg_name: nengo
repo_name: nengo/nengo

copyright_start: 2013

license:
  type: nengo
  append:
    - LICENSE.rst.suppliment

contributing: {}
contributors: {}

manifest:
  graft:
    - nengo-data
  recursive-include:
    - nengo *.rst
    - nengo *.txt

setup_py:
  description: Tools for building and simulating large-scale neural models
  data_files:
    nengo:
      - nengo-data/nengorc
  entry_points:
    nengo.backends:
      - reference = nengo:Simulator
  python_require: ">=3.5"
  install_requires:
    - numpy>=1.11
  docs_requires:
    - sphinx>=1.8
    - jupyter
    - matplotlib>=1.4
    - nbsphinx
    - numpydoc>=0.6
    - nengo_sphinx_theme>=0.8
  optional_requires:
    - scipy>=0.13
    - scikit-learn
  tests_requires:
    - jupyter
    - matplotlib>=1.4
    - pytest>=3.6
  classifiers:
    - "Development Status :: 5 - Production/Stable"
    - "Intended Audience :: Science/Research"
    - "License :: Free for non-commercial use"
    - "Operating System :: OS Independent"
    - "Programming Language :: Python :: 3 :: Only"
    - "Programming Language :: Python :: 3.5"
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"
    - "Topic :: Scientific/Engineering :: Artificial Intelligence"

setup_cfg:
  coverage_omit_lines:
    - "nengo/_vendor/*"
    - "nengo/spa/*"
  flake8_ignore: E123,E133,E226,E241,E242,E501,E731,F401,W503
  pytest_norecursedirs:
    - nengo/_vendor
  pytest_filterwarnings:
    - "ignore:(Buffer|Memory|The nengo\\.spa):DeprecationWarning"
    - "ignore:Skipping some optimization steps"
    - "ignore:SciPy is not installed"
    - "ignore:numpy.(dtype|ufunc) size changed"
  pylint_ignore:
    - compat.py
  pylint_disable:
    - all
    - broad-except
    - cyclic-import
    - import-error
    - reimported
  pylint_enable:
    - anomalous-backslash-in-string
    - assert-on-tuple
    - attribute-defined-outside-init
    - bad-except-order
    - bad-mcs-classmethod-argument
    - bad-super-call
    - bad-whitespace
    - bare-except
    - cell-var-from-loop
    - confusing-with-statement
    - consider-using-enumerate
    - dangerous-default-value
    - deprecated-method
    - function-redefined
    - line-too-long
    - misplaced-comparison-constant
    - no-value-for-parameter
    - notimplemented-raised
    - pointless-string-statement
    - repeated-keyword
    - signature-differs
    - singleton-comparison
    - super-init-not-called
    - too-many-function-args
    - undefined-variable
    - unexpected-keyword-args
    - ungrouped-imports
    - unnecessary-lambda
    - unreachable
    - unused-import
    - useless-else-on-loop
    - useless-object-inheritance
    - wrong-import-order
  pylint_third_party:
    - numpy
    - matplotlib
    - mpl_toolkits
    - pytest


docs_conf_py:
  project_name: Nengo core
  description: Large-scale neural simulation in Python

travis_yml:
  python: 3.6
  bones_install: git+https://github.com/nengo/nengo-bones@no-conda
  global_vars:
    NUMPY_VERSION: numpy
  jobs:
    - stage: basic
      script: static
    - script: test-coverage-scipy
      test_args: --plots
    - script: test-coverage
      test_args: --plots
      python: 3.5
    - stage: advanced
      script: docs
    - env:
        NUMPY_VERSION: numpy==1.11
      cache: false  # disable the cache for one build to make sure that works
    - env:
        NUMPY_VERSION: numpy==1.12
    - env:
        NUMPY_VERSION: numpy==1.13
    - env:
        NUMPY_VERSION: numpy==1.14
    - env:
        NUMPY_VERSION: numpy==1.15
    - dist: xenial
      python: 3.7

ci_scripts:
  - template: static
    pip_install:
      - flake8
    post_commands:
      - flake8 nengo
      - flake8 --ignore=E703,W391 docs
  - template: test
    pip_install:
      - $NUMPY_VERSION
  - template: coverage
    output_name: test-coverage
    pip_install:
      - $NUMPY_VERSION
    coverage: true
  - template: coverage
    output_name: test-coverage-scipy
    pip_install:
      - $NUMPY_VERSION
      - scipy
      - scikit-learn
    coverage: true
  - template: docs
    pip_install:
      - $NUMPY_VERSION
      - scipy
      - matplotlib

codecov_yml: {}
